spring.application.name=novel-backend

# avatars
avatar.upload.path=${user.dir}/uploads/avatars/
avatar.access.prefix=/avatars/

# ????????
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=10MB

# JWT?????????
jwt.secret=your_secret_key_123456
jwt.expire=86400000

logging.level.com.example.novelbackend.mapper=WARN
logging.level.org.apache.ibatis=WARN