spring.application.name=novel-backend

# avatars
avatar.upload.path=${user.dir}/uploads/avatars/
avatar.access.prefix=/avatars/

# covers
cover.upload.path=${user.dir}/uploads/covers/
cover.access.prefix=/covers/

# ????????
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# JWT?????????
jwt.secret=mySuperSecretKeyForJWT256bitsLongEnough123456789
jwt.expire=86400000

logging.level.com.example.novelbackend.mapper=WARN
logging.level.org.apache.ibatis=WARN